## What kind of logging, true = detailed. false = basic.
verbose = true

## Path where all files will be stored.
cache_store = "./test/"
## Maximum time(in seconds to store each file).
cache_time = 86400
## How long before one checkwave(in seconds)
watchdog_interval = 30
## Max amount of files to load on start
initial_load_count = 100

server_url = "http://localhost:3434"